services:
  fail2ban:
    build:
      context: .
      dockerfile: Dockerfile-fail2ban
    image: fail2ban-journald:latest
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: always
    env_file:
      - fail2ban.env
    volumes:
      # Fail2ban-Config + State
      - ./data/fail2ban/fail2ban.d/:/etc/fail2ban/fail2ban.d:ro
      - ./data/fail2ban/jail.d/:/etc/fail2ban/jail.d:ro
      - data_fail2ban:/var/lib/fail2ban
      # Host-Journal (volatile + persistent) and machine-id
      - /run/log/journal:/run/log/journal:ro
      - /var/log/journal:/var/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
    logging:
      # Fail2ban-Logs into Host-Journal
      driver: journald
      options:
        tag: "fail2ban-DC"

volumes:
  data_fail2ban:
