FROM debian:trixie-slim

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  fail2ban python3-systemd iptables whois ca-certificates \
  msmtp-mta mailutils tzdata && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

COPY fail2ban-entrypoint.sh /usr/local/bin/fail2ban-entrypoint.sh
RUN set -Eeuo pipefail; \
  chmod +x /usr/local/bin/fail2ban-entrypoint.sh; \
  mkdir -p /etc/fail2ban; \
  printf '%s\n' \
  '[Definition]' \
  'loglevel = INFO' \
  'logtarget = STDOUT' \
  > /etc/fail2ban/fail2ban.local && \
  printf '%s\n' \
  '[DEFAULT]' \
  'destemail = root' \
  'action    = %(action_mwl)s' \
  'backend   = systemd' \
  'bantime   = 1h' \
  'findtime  = 10m' \
  'maxretry  = 5' \
  'bantime.increment = true' \
  'ignoreip  = 127.0.0.1/8 ::1' \
  > /etc/fail2ban/jail.local

ENTRYPOINT ["/usr/local/bin/fail2ban-entrypoint.sh"]
